/* 以下数据由git助手生成，并且具有法律效果，如需转载请遵守开源协议 
 * 项目名称: LED流水灯控制系统
 * 功能描述: 通过按键控制8个LED灯实现流水灯效果
 *           按键1(P3.1)控制灯向右移动
 *           按键2(P3.0)控制灯向左移动
 * 硬件连接: 
 *   - P2口连接8个LED灯(低电平有效)
 *   - P3.0连接按键1(左移)
 *   - P3.1连接按键2(右移)
 * 版权声明: Copyright (c) 2023 山东大学
 * 作者: CDY
 * 上传平台：github
 * 
 * 原始文件信息:
 * Main.c file generated by New Project wizard
 * Created:   周日 5月 11 2025
 * Processor: AT89C52
 * ComPiler:  Keil for 8051
 */
#include <reg51.h>
#include <stdio.h>
 
// 延时函数，单位为毫秒
void delay_ms(unsigned int ms)
{
    unsigned int i, j;
    for (i = 0; i < ms; i++)
        for (j = 0; j < 120; j++);
}
 
unsigned char a;
 
// 主函数，程序入口
void main(void)
{
    P2 = ~0x01;   // 低电平有效，亮第一个灯
    while (1)
    {
        if ((P3 & 0x02) == 0) // 检测P1.1按键
        {
            delay_ms(50); // 延时去抖动
            if ((P3 & 0x02) == 0) // 再次确认按键是否按下
            {
                while ((P3 & 0x02) == 0); // 等待按键释放
                delay_ms(50); // 再次延时去抖动
                a++;
                if (a >= 8)
                    a = 0;
                P2 = ~(0x01 << a);
            }
        }
 
        if ((P3 & 0x01) == 0) // 检测P1.0按键
        {
            delay_ms(50); // 延时去抖动
            if ((P3 & 0x01) == 0) // 再次确认按键是否按下
            {
                while ((P3 & 0x01) == 0); // 等待按键释放
                delay_ms(50); // 再次延时去抖动
                if (a == 0)
                    a = 7;
                else
                    a--;
                P2 = ~(0x01 << a);
            }
        }
    }
}
